[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "session-splitter"
version = "0.1.0"
description = "todo"
authors = [
    { name="Bruno Schilling", email="bruno.schilling@protonmail.ch" }
]
license = "MIT" 
license-files = ["LICENSE"]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "inaspeechsegmenter>=0.8.0",
    "numpy>=2.4.6",
    "pydub>=0.25.1",
    "pygame>=2.6.1",
    "scipy>=1.17.1",
    "tqdm>=4.70.1",
]

[project.scripts]
session_splitter = "session_splitter.cli.main:main"

[project.optional-dependencies]
dev = ["pytest", "build", "twine"]

[tool.setuptools.packages.find]
where = ["."]
